version: "3"

services:
  postgres:
    image: postgres:12
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: "spiral"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

volumes:
  postgres:
